/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PetLive;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

public class PetHotel extends javax.swing.JFrame implements PetLive{
    public PetHotel() {
        initComponents();
    }
    @Override
    public void close(){
        WindowEvent tutup = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(tutup);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NPemilik = new javax.swing.JLabel();
        NPeliharaan = new javax.swing.JLabel();
        Jenis = new javax.swing.JLabel();
        TglReservasi = new javax.swing.JLabel();
        Harga = new javax.swing.JLabel();
        IsiNamaPemilik = new javax.swing.JTextField();
        IsiNamaPeliharaan = new javax.swing.JTextField();
        IsiHarga = new javax.swing.JTextField();
        IsiTglReservasi = new com.toedter.calendar.JDateChooser();
        KlikBatal = new javax.swing.JButton();
        JmlhHari = new javax.swing.JLabel();
        IsiJenis = new javax.swing.JComboBox<>();
        KlikReservasi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        IsiTglReservasi2 = new com.toedter.calendar.JDateChooser();
        IsiJmlhHari = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NPemilik.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        NPemilik.setText("Nama Pemilik");
        getContentPane().add(NPemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 310, 40));

        NPeliharaan.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        NPeliharaan.setText("Nama Peliharaan");
        getContentPane().add(NPeliharaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 290, 40));

        Jenis.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        Jenis.setText("Jenis");
        getContentPane().add(Jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 300, 40));

        TglReservasi.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        TglReservasi.setText("Tanggal Reservasi");
        getContentPane().add(TglReservasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 280, 40));

        Harga.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        Harga.setText("Harga");
        getContentPane().add(Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 525, -1, 40));

        IsiNamaPemilik.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        getContentPane().add(IsiNamaPemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 233, 510, 38));

        IsiNamaPeliharaan.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        getContentPane().add(IsiNamaPeliharaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 293, 510, 38));

        IsiHarga.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        getContentPane().add(IsiHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 523, 510, 38));

        IsiTglReservasi.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        getContentPane().add(IsiTglReservasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 407, 210, 38));

        KlikBatal.setBackground(new java.awt.Color(0, 204, 153));
        KlikBatal.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        KlikBatal.setForeground(new java.awt.Color(255, 255, 255));
        KlikBatal.setText("Batal");
        KlikBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlikBatalActionPerformed(evt);
            }
        });
        getContentPane().add(KlikBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 160, 50));

        JmlhHari.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        JmlhHari.setText("Jumlah Hari");
        getContentPane().add(JmlhHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 465, -1, 40));

        IsiJenis.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        IsiJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Kucing", "Anjing" }));
        getContentPane().add(IsiJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 351, 510, 38));

        KlikReservasi.setBackground(new java.awt.Color(0, 204, 153));
        KlikReservasi.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        KlikReservasi.setForeground(new java.awt.Color(255, 255, 255));
        KlikReservasi.setText("Reservasi");
        KlikReservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlikReservasiActionPerformed(evt);
            }
        });
        getContentPane().add(KlikReservasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 580, 160, 50));

        jLabel2.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        jLabel2.setText("Sampai");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 412, -1, -1));

        IsiTglReservasi2.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        getContentPane().add(IsiTglReservasi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 407, 200, 38));

        IsiJmlhHari.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        IsiJmlhHari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IsiJmlhHariKeyReleased(evt);
            }
        });
        getContentPane().add(IsiJmlhHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 465, 510, 38));

        Back.setBackground(new java.awt.Color(0, 204, 153));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 40, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/petHotel.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KlikBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlikBatalActionPerformed
        IsiNamaPemilik.setText("");
        IsiNamaPeliharaan.setText("");
        IsiJenis.setSelectedItem("Pilih");
        IsiTglReservasi.setCalendar(null);
        IsiTglReservasi2.setCalendar(null);
        IsiJmlhHari.setText("");
        IsiHarga.setText("");
    //private modifier
    //untuk mengosongkan form saat membatalkan pesanan 
    }//GEN-LAST:event_KlikBatalActionPerformed

    private float lama;
    private float tarif;
    private void IsiJmlhHariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IsiJmlhHariKeyReleased
        lama = Float.parseFloat(IsiJmlhHari.getText());
        
        if(IsiJenis.getSelectedItem().equals("Kucing")){
            tarif = lama * 50000;
            IsiHarga.setText("Rp." + tarif);
        }
        else if (IsiJenis.getSelectedItem().equals("Anjing")){
            tarif = lama * 60000;
            IsiHarga.setText("Rp." + tarif);
        }
    }//GEN-LAST:event_IsiJmlhHariKeyReleased

    private void KlikReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlikReservasiActionPerformed
        this.toBack();
        ReservasiPethotel rp = new ReservasiPethotel("");
        rp.TampilNamaPet.setText(IsiNamaPeliharaan.getText());
        rp.TampilNamaUser.setText(IsiNamaPemilik.getText());
        String pilih1 = IsiJenis.getSelectedItem().toString();
        rp.TampilJenis.setText(pilih1);
        DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
        String tgl = fmt.format(IsiTglReservasi.getDate());
        String tgl2 = fmt.format(IsiTglReservasi2.getDate());
        rp.TampilTanggal.setText(tgl);
        rp.TampilTanggal2.setText(tgl2);
        String pilih2 = IsiJmlhHari.getText();
        rp.TampilJumlahHari.setText(pilih2 + "  Hari");
        rp.TampilHarga.setText(IsiHarga.getText());
        rp.setVisible(true);
        rp.toFront();
        this.setVisible(false);
    }//GEN-LAST:event_KlikReservasiActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        close();
        Pilihan p = new Pilihan();
        p.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetHotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Harga;
    private javax.swing.JTextField IsiHarga;
    private javax.swing.JComboBox<String> IsiJenis;
    private javax.swing.JTextField IsiJmlhHari;
    private javax.swing.JTextField IsiNamaPeliharaan;
    private javax.swing.JTextField IsiNamaPemilik;
    private com.toedter.calendar.JDateChooser IsiTglReservasi;
    private com.toedter.calendar.JDateChooser IsiTglReservasi2;
    private javax.swing.JLabel Jenis;
    private javax.swing.JLabel JmlhHari;
    private javax.swing.JButton KlikBatal;
    private javax.swing.JButton KlikReservasi;
    private javax.swing.JLabel NPeliharaan;
    private javax.swing.JLabel NPemilik;
    private javax.swing.JLabel TglReservasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
