/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PetLive;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

public class ReservasiGrooming extends javax.swing.JFrame implements PetLive{
    public ReservasiGrooming() {
        initComponents();
    }
    @Override
    public void close(){
        WindowEvent tutup = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(tutup);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TampilTanggal = new javax.swing.JLabel();
        TampilWaktuO = new javax.swing.JLabel();
        TampilJenis = new javax.swing.JLabel();
        TampilNamaPet = new javax.swing.JLabel();
        TampilTreatment = new javax.swing.JLabel();
        TampilHarga = new javax.swing.JLabel();
        TampilNamaUser = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        KlikOK = new javax.swing.JButton();
        KlikReservasi2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TampilTanggal.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        TampilTanggal.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(TampilTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 226, 390, 40));

        TampilWaktuO.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        TampilWaktuO.setForeground(new java.awt.Color(102, 102, 102));
        TampilWaktuO.setText("11.00 WIB");
        getContentPane().add(TampilWaktuO, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 380, 40));

        TampilJenis.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        TampilJenis.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(TampilJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 140, 40));

        TampilNamaPet.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        TampilNamaPet.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(TampilNamaPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 200, 40));

        TampilTreatment.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        TampilTreatment.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(TampilTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 390, 40));

        TampilHarga.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        TampilHarga.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(TampilHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 390, 40));

        TampilNamaUser.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        TampilNamaUser.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(TampilNamaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 390, 40));

        jLabel10.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("userlovepet@gmail.com");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 210, 40));

        jLabel9.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("+62 85325350602");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 210, 30));

        jLabel11.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 153));
        jLabel11.setText("Pet Grooming");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, 60));

        jLabel12.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 153));
        jLabel12.setText("Detail User");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 180, 60));

        KlikOK.setBackground(new java.awt.Color(0, 204, 153));
        KlikOK.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        KlikOK.setForeground(new java.awt.Color(255, 255, 255));
        KlikOK.setText("Ok");
        KlikOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlikOKActionPerformed(evt);
            }
        });
        getContentPane().add(KlikOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 510, 160, 50));

        KlikReservasi2.setBackground(new java.awt.Color(0, 204, 153));
        KlikReservasi2.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        KlikReservasi2.setForeground(new java.awt.Color(255, 255, 255));
        KlikReservasi2.setText("Back");
        KlikReservasi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlikReservasi2ActionPerformed(evt);
            }
        });
        getContentPane().add(KlikReservasi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 160, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Group.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 250, 140, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Reservasi grooming.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KlikOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlikOKActionPerformed
        close();
        Success p = new Success();
        p.setVisible(true);
    }//GEN-LAST:event_KlikOKActionPerformed

    private void KlikReservasi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlikReservasi2ActionPerformed
        this.toBack();
        setVisible(false);
        new PetGrooming().toFront();
        new PetGrooming().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_KlikReservasi2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservasiGrooming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservasiGrooming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservasiGrooming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservasiGrooming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservasiGrooming().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KlikOK;
    private javax.swing.JButton KlikReservasi2;
    public javax.swing.JLabel TampilHarga;
    public javax.swing.JLabel TampilJenis;
    public javax.swing.JLabel TampilNamaPet;
    public javax.swing.JLabel TampilNamaUser;
    public javax.swing.JLabel TampilTanggal;
    public javax.swing.JLabel TampilTreatment;
    public javax.swing.JLabel TampilWaktuO;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
